export const Products = [
    {
        id: 1,
        name: "Amoxicillin 500mg",
        Categories: "Antibiotics",
        stock: 250,
        purchase: "$4.20",
        selling: "$8.50",
        expiry: "Dec 15, 2026",
        supplier: "PharmaCorp Ltd",
        status: "In Stock",
    },
    {
        id: 2,
        name: "Metformin 850mg",
        Categories: "Diabetes",
        stock: 18,
        purchase: "$2.10",
        selling: "$5.00",
        expiry: "Aug 20, 2025",
        supplier: "MediSupply Inc",
        status: "Low Stock",
    },
    {
        id: 3,
        name: "Atorvastatin 20mg",
        Categories: "Cardiovascular",
        stock: 0,
        purchase: "$6.80",
        selling: "$14.00",
        expiry: "Mar 30, 2026",
        supplier: "GlobalMed",
        status: "Out Of Stock",
    },
    {
        id: 4,
        name: "Paracetamol 500mg",
        Categories: "Pain Relief",
        stock: 320,
        purchase: "$1.20",
        selling: "$3.50",
        expiry: "Jul 25, 2026",
        supplier: "HealthCare Pharma",
        status: "In Stock",
    },
    {
        id: 5,
        name: "Ibuprofen 400mg",
        Categories: "Pain Relief",
        stock: 45,
        purchase: "$2.50",
        selling: "$6.00",
        expiry: "May 22, 2026",
        supplier: "MediSupply Inc",
        status: "Low Stock",
    },
    {
        id: 6,
        name: "Omeprazole 20mg",
        Categories: "Gastro",
        stock: 120,
        purchase: "$3.20",
        selling: "$7.50",
        expiry: "Feb 18, 2027",
        supplier: "PharmaCorp Ltd",
        status: "In Stock",
    },
    {
        id: 7,
        name: "Cetirizine 10mg",
        Categories: "Allergy",
        stock: 65,
        purchase: "$1.80",
        selling: "$4.50",
        expiry: "Jul 12, 2026",
        supplier: "GlobalMed",
        status: "In Stock",
    },
    {
        id: 8,
        name: "Azithromycin 500mg",
        Categories: "Antibiotics",
        stock: 12,
        purchase: "$5.40",
        selling: "$12.00",
        expiry: "Oct 05, 2025",
        supplier: "HealthCare Pharma",
        status: "Low Stock",
    },
    {
        id: 9,
        name: "Losartan 50mg",
        Categories: "Cardiovascular",
        stock: 90,
        purchase: "$4.10",
        selling: "$9.00",
        expiry: "Dec 25, 2026",
        supplier: "MediSupply Inc",
        status: "In Stock",
    },
    {
        id: 10,
        name: "Insulin Injection",
        Categories: "Diabetes",
        stock: 0,
        purchase: "$15.00",
        selling: "$30.00",
        expiry: "Sep 14, 2025",
        supplier: "GlobalMed",
        status: "Out Of Stock",
    },
    {
        id: 11,
        name: "Vitamin C Tablets",
        Categories: "Supplements",
        stock: 200,
        purchase: "$2.00",
        selling: "$5.50",
        expiry: "Apr 30, 2027",
        supplier: "HealthPlus",
        status: "In Stock",
    },
    {
        id: 12,
        name: "Calcium Tablets",
        Categories: "Supplements",
        stock: 35,
        purchase: "$3.00",
        selling: "$7.00",
        expiry: "Jun 16, 2026",
        supplier: "HealthPlus",
        status: "Low Stock",
    },
    {
        id: 13,
        name: "Aspirin 75mg",
        Categories: "Cardiovascular",
        stock: 140,
        purchase: "$1.50",
        selling: "$4.00",
        expiry: "Mar 08, 2027",
        supplier: "PharmaCorp Ltd",
        status: "In Stock",
    },
    {
        id: 14,
        name: "Doxycycline 100mg",
        Categories: "Antibiotics",
        stock: 8,
        purchase: "$4.80",
        selling: "$11.00",
        expiry: "Nov 20, 2025",
        supplier: "MediSupply Inc",
        status: "Low Stock",
    },
    {
        id: 15,
        name: "Cough Syrup",
        Categories: "Cold & Flu",
        stock: 75,
        purchase: "$3.50",
        selling: "$8.00",
        expiry: "Jan 15, 2026",
        supplier: "HealthCare Pharma",
        status: "In Stock",
    },
    {
        id: 16,
        name: "Salbutamol Inhaler",
        Categories: "Respiratory",
        stock: 0,
        purchase: "$8.00",
        selling: "$18.00",
        expiry: "Aug 28, 2025",
        supplier: "GlobalMed",
        status: "Out Of Stock",
    },
    {
        id: 17,
        name: "Prednisolone 10mg",
        Categories: "Steroids",
        stock: 55,
        purchase: "$2.70",
        selling: "$6.50",
        expiry: "Feb 05, 2027",
        supplier: "PharmaCorp Ltd",
        status: "In Stock",
    },
    {
        id: 18,
        name: "Pantoprazole 40mg",
        Categories: "Gastro",
        stock: 22,
        purchase: "$3.60",
        selling: "$8.20",
        expiry: "May 19, 2026",
        supplier: "MediSupply Inc",
        status: "Low Stock",
    },
    {
        id: 19,
        name: "Hydroxychloroquine 200mg",
        Categories: "General Medicine",
        stock: 100,
        purchase: "$5.00",
        selling: "$12.50",
        expiry: "Dec 12, 2026",
        supplier: "HealthPlus",
        status: "In Stock",
    },
    {
        id: 20,
        name: "Multivitamin Capsules",
        Categories: "Supplements",
        stock: 0,
        purchase: "$4.00",
        selling: "$10.00",
        expiry: "Oct 10, 2025",
        supplier: "GlobalMed",
        status: "Out Of Stock",
    }
];